// TOOLS
export const FILL_TOOL_LIST = "FILL_TOOL_LIST";
export const ADD_TO_WORK_PANEL = "ADD_TO_WORK_PANEL";
export const MOVE_ITEM_ON_WORK_PANEL = "MOVE_ITEM_ON_WORK_PANEL";

// LOGS
export const ADD_NEW_LOG = "ADD_NEW_LOG";

// ARROWS
export const ADD_NEW_ARROW = "ADD_NEW_ARROW";
