import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Grid, Toolbar, AppBar, ButtonGroup, Button } from '@material-ui/core';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid container>
        <Grid item xs={12}>
          <AppBar position="static">
            <Toolbar variant="dense">
            <ButtonGroup variant="text" aria-label="small outlined button group">
              <Button size="small" variant="contained">File</Button>
              <Button size="small" variant="contained">Window</Button>
              <Button size="small" variant="contained">Edit</Button>
              <Button size="small" variant="contained">Navigation</Button>
            </ButtonGroup>
            </Toolbar>
          </AppBar>
        </Grid>
        <Grid container className={styles.workPanel}>
          <Grid item md={2} className={styles.listPanel}>
            List Panel
          </Grid>
          <Grid container direction="column" md={8}>
            <Grid item className={styles.designPanel}>
              Design Panel
            </Grid>
            <Grid item className={styles.errorPanel}>
              Error Panel
            </Grid>
          </Grid>
          <Grid item md={2} className={styles.toolPanel}>
            Tool Panel
          </Grid>
        </Grid>
      </Grid>

      {/*
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}

export default Home
